version: '3.8'

services:
  server:
    container_name: TCPServer
    ports:
      - "5678:5678"
    build:
      context: .
      dockerfile: compose/TCPServer/Dockerfile
    networks:
      - external_network

networks:
  external_network:
    driver: bridge