version: '3.8'

services:
  server:
    container_name: TCPServer
    ports:
      - "5678:5678"
    build:
      context: .
      dockerfile: compose/TCPServer/Dockerfile
    volumes:
      - cloud:/tmp/cloud
    networks:
      - external_network

volumes:
  cloud:
networks:
  external_network:
    driver: bridge