COMPILER=gcc
FLAGS=-o

run:
	$(COMPILER) father.c $(FLAGS) father
	$(COMPILER) son1.c $(FLAGS) son1
	$(COMPILER) son2.c $(FLAGS) son2
	$(COMPILER) son3.c $(FLAGS) son3
	./father

clear:
	rm father son1 son2 son3