from .dominance_mechanism import calculate_dominance, calculate_dominance_results_by_variant
from .k_max_mechanism import calculate_k_max_options, calculate_k_max_results_by_variant
from .locking_mechanism import calculate_lock, calculate_lock_results_by_variant
from .tournament_mechanism import calculate_tournament, calculate_tournament_results_by_variant
